language: go

go:
  - 1.3
  - 1.4
  - 1.5

install:
  - rm -rf $GOPATH/src/gopkg.in/src-d
  - mkdir -p $GOPATH/src/gopkg.in/src-d
  - ln -s $PWD $GOPATH/src/gopkg.in/src-d/go-git.v2
  - go get -v -t ./...

script:
  - go test -v ./...

script:
  - go test -v gopkg.in/src-d/go-git.v2 -covermode=count -coverprofile=coverage.out
  - go test -v gopkg.in/src-d/go-git.v2/clients/common -covermode=count -coverprofile=tmp.out
  - tail -n +2 tmp.out >> coverage.out
  - go test -v gopkg.in/src-d/go-git.v2/clients/http -covermode=count -coverprofile=tmp.out
  - tail -n +2 tmp.out >> coverage.out
  - go test -v gopkg.in/src-d/go-git.v2/packfile -covermode=count -coverprofile=tmp.out
  - tail -n +2 tmp.out >> coverage.out
  - go test -v gopkg.in/src-d/go-git.v2/formats/pktline -covermode=count -coverprofile=tmp.out
  - tail -n +2 tmp.out >> coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)
