language: go

go:
  - 1.8
  - tip

go_import_path: gopkg.in/src-d/go-git.v4

env:
  - GIT_VERSION=master
  - GIT_VERSION=v1.9.3
  - GIT_VERSION=v2.11.0

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

cache:
  directories:
  - $HOME/.git-dist

before_script:
  - export GIT_DIST_PATH=$HOME/.git-dist
  - make build-git

before_install:
  - eval "$(ssh-agent -s)"
  # we only decrypt the SSH key when we aren't in a pull request
  #- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash .travis/install_key.sh; fi'
  #- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export SSH_AUTH_SOCK="" ; fi'\
  # temporal fix skip of SSH test
  - export SSH_AUTH_SOCK=""
  - git config --global user.email "travis@example.com"
  - git config --global user.name "Travis CI"

install:
  - go get -v -t ./...

script:
  - export GIT_EXEC_PATH=$GIT_DIST_PATH
  - export PATH=$GIT_DIST_PATH:$PATH
  - git version
  - make test-coverage
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)